package com.exceptionpractice;

import java.util.Arrays;
import java.util.Scanner;

public class ExceptionPractice {

	public static void main(String[] args) {
		Scanner scan = new Scanner(System.in);
		
////		Question 1
//		System.out.println("Enter any two numbers");
//		int n1 = scan.nextInt();
//		int n2= scan.nextInt();
//		try {
//			System.out.println(n1/n2);
//		}catch(ArithmeticException e) {
//			System.err.println( e.getMessage());
//		}
		
//		Question 2
//		int arr[] = new int [10];
//		System.out.println(Arrays.toString(arr));
//		try {
//			arr[6] = 5;
//			System.out.println("Executed");
//		} catch (ArrayOutOfBoundException e) {
//			e.getMessage();
//		}
//		
		
		//Question 3
		String s = null;
		try {
			System.out.println(s.length());
		}
		
	}

}
